baseurl = "http://www.gregboggs.com"
title = "Portland Drupal Developer"
uglyurls = false
paginate = 10
Author = "Greg Boggs"

[permalinks]
  blog = "/:slug"
  form = "/:slug"
  page = "/:slug"

[params]
  Author = "Greg Boggs"
  DateForm = "Jan 2, 2006"
  googleAnalytics = "UA-18809802-1"
  jquery = "2.1.4"
  SyntaxHighlightTheme = "solarized_dark.min.css"
  
  #Starter theme specifics
  tagline = "Portland Drupal Developer"
  intro = "I make websites that <strong>succeed.</strong>"
  github = "https://github.com/Greg-Boggs/"
  linkedin = "https://www.linkedin.com/in/gregoryboggs"
  twitter = "https://twitter.com/gregory_boggs"

[Indexes]
  categories = "categories"

[[menu.top]]
    name = "Blog"
    url = "/blog/"
[[menu.blog]]
    name = "Build Your Own House"
    url = "https://www.byoh.com" 
[[menu.blog]]
    name = "Scan WP"
    url = "http://www.scanwp.com"
[[menu.blog]]
    name = "Game Solver"
    url = "https://www.gamesolver.info/"
[[menu.blog]]
    name = "CSS Complexity"
    url = "http://css.gregboggs.com"
[[menu.blog]]
    name = "Hugo Starter Theme"
    url = "https://github.com/Greg-Boggs/starter"
[[menu.blog]]
    name = "Wesnoth Gaming Ladder"
    url = "http://sourceforge.net/projects/gamingladder/"
[[menu.blog]]
    name = "Elijah Lynn's Blog"
    url = "https://www.elijahlynn.net"
